spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


    datasource:
      url: jdbc:postgresql://localhost:5432/mydatabase
      usernamse: myuser
      password: secret
      driver-class-name: org.postgresql.Driver

task-manager-ms:
  message: "Welcome webwook to PROD after Actuator BUS and RabbitMQ Task Manager related local APIs changed in GIT using cipher"
  contactDetails:
    name: "Julio Valsesia - Software Engineer"
    email: "{cipher}ee9f616d870660dc08a01a8e7f3a2a0e348c2313609056398f335dc0f409fce3bfa31eb831ff2d2f91e88079f6359d2d"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
